# Generated by Django 5.0.6 on 2024-07-23 16:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collageaapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('studentname', models.CharField(max_length=225)),
                ('Address', models.CharField(max_length=225)),
                ('Age', models.IntegerField(null=True)),
                ('Date', models.DateField(null=True)),
                ('course', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='collageaapp.addcourse')),
            ],
        ),
    ]
